### PR TITLE
controller patch bugfix

### PR DESCRIPTION
**Pull request by ghost**
prevents patch from bricking DSDT in some circumstances

### CODE REVIEW

**Comment by alexandred** [comment]
What system are you applying the patch where it breaks?

**Comment by ghost** [comment]
I got the attached DSDT from another user. Not completely sure, but this is from either an Xiaomi Mi 12" Skylake oder his new 2017 Xiaomi Mi Pro Coffee Lake. I can ask for more details, if necessary.
[DSDT.zip](https://github.com/alexandred/VoodooI2C-Patches/files/1610169/DSDT.zip)

**Comment by alexandred** [comment]
This device isn't Skylake and doesn't require a controller patch as is specified in the installation instructions.

**Comment by ghost** [comment]
The Xiaomi Mi 12" Skylake is Skylake based...

**Comment by alexandred** [comment]
The DSDT you sent me is not consistent with a Skylake machine. In your post you admitted you were not sure whether the machine is Skylake or Coffeelake. Based on my analysis of the DSDT, it is Coffeelake but you should really just tell me what the machine actually is.

**Pull request closed without merging**
